### ISSUE TITLE
Make descriptors available in usbmon backend

### ISSUE THREAD

**Issue by FFY00** [usb-tools/ViewSB#58]
I think one place this could really improve over Wireshark is by (optionally) having the descriptors in one tab/part of the frontend. Would this be something you are open to add?

**Comment by FFY00** [comment]
I realized this is only available on certain backends and is why it is not working with usbmon.

**Comment by Qyriad** [comment]
I don't think there's anything about the usbmon backend that means ViewSB *can't* show the descriptors—so long as it sees the GET_DESCRIPTOR request, and usbmon should be very capable of observing things at that high a level—so I think this might actually be a bug, but I'll need to look at it more.

Going to reopen this for now at least until I look at it probably next week.

**Comment by FFY00** [comment]
Actually in usbmon ViewSB could be proactive and go ask the kernel for the descriptors.

**Comment by Qyriad** [comment]
True, and if I recall correctly `lsusb` does that if it has the permissions (as opposed to asking the kernel for its stored descriptors), but at the least I wouldn't want ViewSB to do that automatically since that would affect the USB traffic, so ideally there would be a UI button to trigger it. But currently the frontend can't communicate to the backend. Frontend/analyzer/backend communication is something that's very desirable and planned (#39), but will take a non-trivial amount of work.

As for this issue: I'm seeing descriptors just fine on my machine with usbmon, unless you mean something different than "details" panel in this screenshot? 
![image](https://user-images.githubusercontent.com/1542224/94545547-e7b08a80-0209-11eb-82ad-c76b54a23194.png)

**Comment by mossmann** [comment]
@FFY00 Is the view shown above what you were looking for, or were you imagining a separate display that aggregates information from descriptors?

**Comment by FFY00** [comment]
Yes, though the issue title is outdated.

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
